steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
    - build
    - "--tag=gcr.io/$PROJECT_ID/apigee-cicd/jenkins"
    - "--file=./classic/Dockerfile"
    - .
images:
  - "gcr.io/$PROJECT_ID/apigee-cicd/jenkins"
