apiVersion: v1
kind: Namespace
metadata:
  name: example-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: example-backend
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: example-backend
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 80
